spring.application.name=study-flow

# Import local configuration if it exists
spring.config.import=optional:classpath:application-local.properties

# JPA settings for local development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true